// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bot

import (
	"github.com/google/wire"
	"github.com/jayp0521/Translate/utils"
	"gopkg.in/telebot.v3"
	"os"
	"sync"
	"time"
)

// Injectors from wire.go:

func injectBot() TBot {
	sugaredLogger := utils.ProvideLogger()
	botBotKey := provideBotKey()
	settings := provideTeleBotSettings(botBotKey)
	telebotBot := provideTeleBot(settings)
	tBot := TBot{
		log: sugaredLogger,
		key: botBotKey,
		Bot: telebotBot,
	}
	return tBot
}

// wire.go:

var (
	bot     TBot
	botInit sync.Once
)

var SuperSet = wire.NewSet(
	ProvideBot,
)

func provideBotKey() botKey {
	secret := os.Getenv("BOT_KEY")
	if len(secret) == 0 {
		panic("BOT_KEY is not defined!")
	}
	return botKey(secret)
}

func provideTeleBotSettings(key botKey) telebot.Settings {
	return telebot.Settings{
		Token:   string(key),
		Poller:  &telebot.LongPoller{Timeout: 10 * time.Second},
		Verbose: true,
	}
}

func provideTeleBot(settings telebot.Settings) *telebot.Bot {
	b, err := telebot.NewBot(settings)
	if err != nil {
		panic(err)
	}
	return b
}

func ProvideBot() TBot {
	botInit.Do(func() {
		bot = injectBot()
	})
	return bot
}
